port: 4006
email: paradia@algonquincollege.com
url: "https://alainparadis.github.io"
baseurl: "/program-promotion"
github_username:  "alainparadis"
repository: alainparadis/program-promotion
plugins:
  - jekyll-feed

collections:
  schools:
    output: true
    permalink: /schools/:name/

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/